### PR TITLE
Update LibreSignal.

### PR DESCRIPTION
**Pull request by mimi89999**

### CODE REVIEW

**Comment by mimi89999** [comment]
@xmikos

**Comment by mimi89999** [comment]
@xmikos When will you update LibreSignal in your F-Droid experimental repo?

**Comment by mimi89999** [comment]
@xmikos When will you update the app in your F-Droid repo?

**Comment by xmikos** [comment]
Sorry, I want to make this build in reproducible environment but didn't have time to make F-Droid Vagrant buildserver to work :-/ But I should have time in another few hours...

**Pull request merged**
