### PR TITLE
Update LibreSignal

### PR DESCRIPTION
**Pull request by mimi89999**

### CODE REVIEW

**Comment by mimi89999** [comment]
And please run `./gradlew clean` before building.

**Comment by mimi89999** [comment]
The apk of LS 3.14.2 in your repo is 13,9 MiB, but the apk in the F-Droid archive repo is 11,7 MiB...

**Comment by xmikos** [comment]
Thanks, merged, I will build it soon (I want to first review diff).

About that size difference - could it be caused by different build environment? How does build file from official fdroid repo differ from my build file?

**Comment by mimi89999** [comment]
https://gitlab.com/fdroid/fdroiddata/merge_requests/1308/diffs

**Comment by mimi89999** [comment]
What is your build environment?

**Comment by mimi89999** [comment]
That's a bit concerning that the 2 apks aren't the sams size.

**Comment by xmikos** [comment]
Arch Linux, latest Android SDK. I will compare unziped apks.

**Comment by xmikos** [comment]
@mimi89999 Does F-Droid somewhere specify their build environment for reproducible builds? We can't have completely reproducible builds because I am using different app name, but we can at least get as close as possible.

**Comment by mimi89999** [comment]
Well, there is the "build environment" section in the manual.

**Comment by xmikos** [comment]
@mimi89999 I have found what is causing that big size difference, it is `libredphone-audio.so` library, it is included in my build but not in F-Droid build.

**Pull request merged**
